#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "gcc -I/home/semih/packetngin/lib/../lib/newlib/newlib/libc/include -ffreestanding -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_SYSNAME_PACKETNGIN -DOPENSSL_NO_SOCK -DOPENSSL_NO_DGRAM -DOPENSS_NO_SCTP -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM"
  #define PLATFORM "packetngin-x86_64"
  #define DATE "Fri May 30 00:00:27 KST 2014"
#endif
