/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <unistd.h>
#include "rpc_callback.h"

void* callback_null_1_svc(struct svc_req *rqstp) {
	static char* result;
	return (void*) &result;
}

void* stdio_1_svc(RPC_Message message,  struct svc_req *rqstp) {
	static char* result;
	
	char buffer[64] = { 0, };
	int len = sprintf(buffer, "%lu %d %d> ", message.vmid, message.coreid, message.fd);
	write(0, buffer, len);
	write(0, message.message.message_val, message.message.message_len);
	
	return (void*)&result;
}
