# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Manager_config = debug
endif
ifeq ($(config),release)
  Manager_config = release
endif

PROJECTS := Manager

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Manager:
ifneq (,$(Manager_config))
	@echo "==== Building Manager ($(Manager_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(Manager_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Manager"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"