#!/bin/sh
### BEGIN INIT INFO
# Provides:				packetngin
# Required-Start:		$network $syslog
# Required-Stop:		$network $syslog
# Default-Start:		2 3 4 5
# Default-Stop:
# Short-Description:	PacketNgin RTOS manager
# Description:       	PacketNgin Real-time Operating System Manager
### END INIT INFO

MANAGER_DIR=$HOME/manager
MANAGER_PID_FILE=/var/run/manager.pid
MANAGER_CONFIG_FILE=$MANAGER_DIR/boot_args_1.param

DAEMON=$MANAGER_DIR/manager

#MANAGER_DEVICE_MODULE=virtio_accel
#LINUX_DEVICE_MODULE=virtio_net

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

insert_module() {
    if [ -z "$1" ]; then
        return 1
    fi

    sudo modprobe $1
    if [ $? -eq 0 ]; then
        log_warning_msg "Loading network device driver module '$1'"
    else
		return 1
    fi

	return 0
}

remove_module() {
    if [ -z "$1" ]; then
        return 1
    fi

    lsmod | grep -ws $1 > /dev/null
    if [ $? -eq 0 ] ; then
        log_warning_msg "Unloading network device driver module '$1'"
        sudo rmmod $1
    else
        return 1
    fi

	return 0
}

cmd_start() {
    log_daemon_msg "Staring PacketNgin manager daemon"

    #remove_module $LINUX_DEVICE_MODULE
    #if ! insert_module $MANAGER_DEVICE_MODULE; then
        #log_failure_msg "Failed to load device module '$MANAGER_DEVICE_MODULE'"
        #log_end_msg 1
        #exit 1
    #fi

    if [ -s "$MANAGER_PID_FILE" ] \
        && kill -0 $(cat $MANAGER_PID_FILE) > /dev/null 2>&1; then
        log_warning_msg "PacketNgin manager already running"
        log_end_msg 1
        exit 1
    fi

    if [ ! -s "$MANAGER_CONFIG_FILE" ]; then
        log_failure_msg \
            "Multikernel boot configuration file '$MANAGER_CONFIG_FILE' required"
        log_end_msg 1
        exit 1
    fi

    if start-stop-daemon --start --background --pidfile $MANAGER_PID_FILE \
        --make-pidfile --chdir $MANAGER_DIR --exec $DAEMON -- $MANAGER_CONFIG_FILE > /home/gurum/t
    then
        rc=0
        sleep 1
        if ! kill -0 $(cat $MANAGER_PID_FILE) > /dev/null 2>&1; then
            log_failure_msg "Failed to start PacketNgin manager"
            rc=1
        fi
    else
        rc=1
    fi

    if [ $rc -eq 0 ]; then
        log_end_msg 0
    else
        log_end_msg 1
        rm -f $MANAGER_PID_FILE
    fi
}

cmd_stop() {
	log_daemon_msg "Stopping PacketNgin manager daemon"

	start-stop-daemon --stop --quiet --oknodo --pidfile $MANAGER_PID_FILE
	log_end_msg $?

    sleep 1

    #remove_module $MANAGER_DEVICE_MODULE
    #if ! insert_module $LINUX_DEVICE_MODULE; then
        #log_failure_msg "Failed to load device module '$LINUX_DEVICE_MODULE'"
        #log_end_msg 1
        #exit 1
    #fi

	rm -f $MANAGER_PID_FILE
}

cmd_status() {
    status_of_proc -p $MANAGER_PID_FILE "$DAEMON" manager
    exit $?
}

case "$1" in
    start)
        cmd_start
        ;;

    stop)
        cmd_stop
        ;;

    restart)
        cmd_stop
        cmd_start
        ;;

    status)
        cmd_status
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
