/*
 * Automatically generated C config: don't edit
 * libpayload version: 0.2.0
 * Fri May 29 16:12:02 2015
 */
#define AUTOCONF_INCLUDED
#define CONFIG_LP_SPEAKER 1
#define CONFIG_LP_STORAGE 1
#define CONFIG_LP_LIBC 1
#define CONFIG_LP_USB_HID 1
#define CONFIG_LP_VGA_VIDEO_CONSOLE 1
#define CONFIG_LP_ARCH_X86 1
#define CONFIG_LP_STORAGE_ATA 1
#define CONFIG_LP_ARCH_SPECIFIC_OPTIONS 1
#define CONFIG_LP_STORAGE_AHCI_ONLY_TESTED 1
#define CONFIG_LP_OBSOLETE 1
#define CONFIG_LP_TIMER_RDTSC 1
#define CONFIG_LP_CHROMEOS 1
#define CONFIG_LP_NVRAM 1
#define CONFIG_LP_STORAGE_AHCI 1
#define CONFIG_LP_EXPERIMENTAL 1
#define CONFIG_LP_REMOTEGDB 1
#define CONFIG_LP_MEMMAP_RAM_ONLY 1
#define CONFIG_LP_DEVELOPER 1
#define CONFIG_LP_IO_ADDRESS_SPACE 1
#define CONFIG_LP_LITTLE_ENDIAN 1
#define CONFIG_LP_PCI 1
#define CONFIG_LP_STORAGE_ATAPI 1
#define CONFIG_LP_GPL 1
#define CONFIG_LP_VIDEO_CONSOLE 1
#define CONFIG_LP_STORAGE_64BIT_LBA 1

#define CONFIG_LP_USB_EHCI_HOSTPC_ROOT_HUB_TT 1
#define CONFIG_LP_USB 1
#define CONFIG_LP_USB_PCI 1
#define CONFIG_LP_USB_HUB 1
#define CONFIG_LP_USB_MSC 1
#define CONFIG_LP_USB_GEN_HUB 1
#define CONFIG_LP_USB_EHCI 1
