#!/bin/bash

## This file is for PacketNgin Bash Wrapper. 
## Usage: source connect [IP] [PORT]

DEFAULT_MANAGER_IP="10.0.0.2"
DEFAULT_MANAGER_PORT="1111"

IP=${1:-${DEFAULT_MANAGER_IP}}
PORT=${2:-${DEFAULT_MANAGER_PORT}}

OLD_PATH="$PATH"
OLD_PS1="$PS1"

disconnect() {
    if ! [ -z "${PATH}" ]; then
        PATH="$OLD_PATH"
        export PATH
        unset OLD_PATH
    fi

    if ! [ -z "${PS1}" ]; then
        PS1="$OLD_PS1"
        export PS1 
        unset OLD_PS1
    fi

    unset MANAGER_IP
    unset MANAGER_PORT
    unset disconnect
}

connect() {
    ./bin/connect $IP $PORT
    if [ $? -eq 0 ]; then
        echo "PacketNgin Manager Connected to $IP:$PORT"
        PATH="./bin:$PATH"
        PS1="PacketNgin Bash > "
        export MANAGER_IP=${IP}
        export MANAGER_PORT=${PORT}
        export PATH
        export PS1
    else
        echo "PacketNgin Manager Disconnected"
    fi
}

connect
